name: My Test Workflow

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs: 
  ci:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 
        uses: actions/setup-node@v3
        with: 
          node-version: '16.x'
          
      - name: Install npm 
        run: npm install

      - name: Run Lint
        run: npm run lint
        continue-on-error: false

      - name: Run Tests
        run: npm test

      - name: Code coverage-reporter
        uses: tj-actions/coverage-reporter@v5
        with:
          token: ${{ github.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 }}
          # Specify a coverage command to run the test.
          # coverage-command:
  cd:
      needs: ci
      runs-on: ubuntu-latest
      steps: 
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Use Node.js 
        uses: actions/setup-node@v4
        with: 
          node-version: '16.x'

      - name: Install npm 
        run: npm install

      - name: Run Build
        run: npm run build
          

