name: My Test Workflow

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs: 
  ci:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3.2.2
  cd:
      runs-on: ubuntu-latest
      steps: 
      - name: Checkout
        uses: actions/checkout@v3.2.2
