name: My Test Workflow

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
          
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0

      - name: Install Dependencies
        run: npm i
      - name: Run Tests
        run: npm test
        
      - name: Install modules
        run: npm init @eslint/config@latest
      - name: Run ESLint
        run: npm run eslint
